service/thefakebook/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.views.static import serve
from django.urls import path
from django.views.generic import RedirectView

from core.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^profile$', profile),
    url(r'^profile/(?P<profile_id>\d{1,50})$', profile),
    url(r'^profile/edit$', profile_edit),
    url(r'^profile/pic_edit$', picture_edit),
    url(r'^search$', search_result),
    url(r'^index$', index),
    url(r'^schools_supported$', schools_supported),
    url(r'^contact_us$', contact_us),
    url(r'^terms_of_use$', terms_of_use),
    url(r'^register$', register),
    url(r'^login$', signin),
    url(r'^logout$', signout),
    url(r'^profile/(?P<profile_id>\d{1,50})/add_to_friend$', add_friend),
    url(r'^profile/(?P<profile_id>\d{1,50})/remove_from_friend$', remove_friend),
    url(r'^friends$', friends),
    url(r'^friends/requests$', friends_requests),
    url(r'^messages$', all_messages),
    url(r'^messages/(?P<profile_id>\d{1,50})$', messages_view),
    url(r'^$', RedirectView.as_view(url='index')),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': "core/static"}),
]

service/core/models.py
from django.contrib.auth.models import User
from django.db import models
from core.school_choices import SCHOOL_CHOICES
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to="core/static/avatars/")
    account_info = models.OneToOneField(        "AccountInfo", on_delete=models.CASCADE)
    basic_info = models.OneToOneField( "BasicInfo", on_delete=models.CASCADE)
    contact_info = models.OneToOneField(      "ContactInfo", on_delete=models.CASCADE, blank=True, null=True)
    friends = models.ManyToManyField(                                         "Profile", through="Friendship")
    def __str__(self):
        return self.account_info.name
class AccountInfo(models.Model):
    name = models.CharField(max_length=128)
    member_since = models.DateTimeField(auto_now_add=True)
    last_update = models.DateTimeField(auto_now=True)
class BasicInfo(models.Model):
    SEX_CHOICES = (("M", "Male"), ("W", "Women"))
    STATUS_CHOICES = ((1, "Student (Full-Time)"),
(2, "Alumnus/Alumna"), (3, "Faculty"), (4, "Staff"), (5, "Grad Student"))
    school = models.PositiveIntegerField(choices=SCHOOL_CHOICES, blank=True, null=True)
    status = models.PositiveSmallIntegerField(choices=STATUS_CHOICES)
    sex = models.CharField(max_length=1,         choices=SEX_CHOICES, blank=True)
    birthday = models.DateField(     blank=True, null=True)
    hometown = models.CharField(max_length=128,             blank=True)
    high_school = models.CharField(max_length=128,     blank=True)
class ContactInfo(models.Model):
    looking_for = models.CharField(max_length=258,  blank=True)
    interested_for = models.CharField(max_length=258,      blank=True)
    political_views = models.CharField(max_length=258,  blank=True)
    interests = models.CharField(max_length=258,        blank=True)
    clubs_and_jobs = models.CharField(   max_length=258, blank=True)
    favorite_books = models.CharField(  max_length=258, blank=True)
    favorite_movies = models.CharField(  max_length=258, blank=True)
    about_me = models.CharField(  max_length=512, blank=True)
class Friendship(models.Model):
    STATUS_CHOICES = (   (1, "Request for friendship"),
        (         2, "Request accepted"), (3, "Request denied"))
    request_from = models.ForeignKey("Profile",        on_delete=models.CASCADE,
                                     related_name="request_from")
    request_to = models.ForeignKey("Profile", on_delete=models.CASCADE,

                                   related_name="request_to")
    status = models.PositiveSmallIntegerField(choices=STATUS_CHOICES)
    created = models.DateTimeField(auto_now_add=True)
class Message(models.Model):
    message_from = models.ForeignKey(  Profile,  on_delete=models.CASCADE,              related_name="message_from")
    message_to = models.ForeignKey(Profile,
                    on_delete=models.CASCADE,
               related_name="message_to")
    readed = models.BooleanField(
        default=False)
    created = models.DateTimeField(
        auto_now_add=True)
    title = models.CharField(max_length=35)
    body = models.TextField()

service/core/views.py
import re
import datetime

from django.db.models import Q as Я
from django.http import Http404
from django.contrib.auth.models import User as ʼʽʾʿ

from django.shortcuts import render, redirect
from core.school_choices import SCHOOL_CHOICES
from django.core.validators import validate_email
from django.contrib.auth.decorators import login_required as Декоратор_гыг
from django.contrib.auth import authenticate, login, logout
from core.models import Profile as ݒݓݔ
from core.models import AccountInfo as ɾɿ
from core.models import BasicInfo as ఋఌఱశಣಹఋೲ
from core.models import ContactInfo as ಅಘౙపఠಖనల

from core.models import Friendship, Message
def get_avatar_url(амлет_кушать): return амлет_кушать.avatar.url[4:] if амлет_кушать.avatar else "/static/noimage.jpg"
ۮۯۺۻۼ = dict
def JUST_DO_IT(НЕНАВИСТЬ):
    def wrapper(Мимими, *args, **kwargs):
        if Мимими.user.is_authenticated:
            if hasattr(Мимими.user, "profile"):
                ЯросТЬЬЬ = Мимими.user.profile; ОГонЬ1 = False
                if not hasattr(ЯросТЬЬЬ, "basic_info"): Мимими.user.profile["basic_info"] = ఋఌఱశಣಹఋೲ.objects.create(status=4); ОГонЬ1 = True;
# from pep8
# with love
#     ♥
                if not hasattr(ЯросТЬЬЬ, "account_info"): Мимими.user.profile["account_info"] = ɾɿ.objects.create(name=Мимими.user.username); ОГонЬ1 = True;
                if not hasattr(ЯросТЬЬЬ, "contact_info"): Мимими.user.profile["contact_info"] = ಅಘౙపఠಖనల.objects.create(); ОГонЬ1 = True;
                if ОГонЬ1: Мимими.user.profile.save()
            else:
                data = ۮۯۺۻۼ(); data["user"] = Мимими.user; data["basic_info"] = ఋఌఱశಣಹఋೲ.objects.create(status=4);
                data["account_info"] = ɾɿ.objects.create(name=Мимими.user.username); data["contact_info"] = ಅಘౙపఠಖనల.objects.create();

                ݒݓݔ.objects.create(**data)
        return НЕНАВИСТЬ(Мимими, *args, **kwargs)
    return wrapper
ಈಈಗడಒಯಱಜ = Friendship
@JUST_DO_IT
def index(грог):
    if грог.user.is_authenticated:
        username = грог.user.profile.account_info.name;
        count_rec_req = ಈಈಗడಒಯಱಜ.objects.filter(request_to=грог.user.profile, status=1).count();
        count_friends = ಈಈಗడಒಯಱಜ.objects.filter(request_from=грог.user.profile, status=2).count();
        return render(грог, 'aftersignin/welcome_page.html', {'username': username,
                                                                                                "user": грог.user, "count_rr": count_rec_req, "count_fr": count_friends})
    else:
        return render(грог, 'beforesignin/welcome_page.html')
def schools_supported(request):
    return render(request, 'beforesignin/schools_supported.html', {"user": request.user})
def contact_us(request):
    return render(request, 'beforesignin/contact_us.html', {"user": request.user})
నథಉఓಬಔಠಯ = Message
def terms_of_use(request):
    return render(request, 'beforesignin/terms_of_use.html', {"user": request.user})

def register(ОТДыХХ):
    if ОТДыХХ.method == 'POST':
        КоПиЯЯ = ОТДыХХ.POST.get("email"); сИМВОЛ = ОТДыХХ.POST.get("name"); passw = ОТДыХХ.POST.get("pass");
        Жалкая_пародия = ОТДыХХ.POST.get("status"); terms = ОТДыХХ.POST.get("terms");
        if not (КоПиЯЯ and сИМВОЛ and passw and Жалкая_пародия):
            return render(ОТДыХХ, "beforesignin/register.html", {

                                        "error": "All parametrs needed!", "user": ОТДыХХ.user})
        if terms != "1": return render(ОТДыХХ,
                                "beforesignin/register.html", {"error": "Please read the Term of use, please!", "user": ОТДыХХ.user})
        сИМВОЛ = сИМВОЛ.replace("+", " ") if сИМВОЛ else None; Жалкая_пародия = int(Жалкая_пародия) if Жалкая_пародия.isdigit() else None;
        try:
            validate_email(КоПиЯЯ);
        except:
            return render(ОТДыХХ, "beforesignin/register.html", {"error": "Email is not valid!", "user": ОТДыХХ.user})

        try:
            цтф_это_дружба = ʼʽʾʿ.objects.create_user(КоПиЯЯ, КоПиЯЯ, passw); login(ОТДыХХ, цтф_это_дружба);
        except:
            return render(ОТДыХХ, "beforesignin/register.html", {"error": "You're already registered!", "user": ОТДыХХ.user})
        account_info = ɾɿ.objects.create(name=сИМВОЛ); basic_info = ఋఌఱశಣಹఋೲ.objects.create(
            status=Жалкая_пародия);
        contact_info = ಅಘౙపఠಖనల.objects.create(); ݒݓݔ.objects.create(user=цтф_это_дружба, account_info=account_info, basic_info=basic_info, contact_info=contact_info);
        return redirect("/index")
    return render(ОТДыХХ, "beforesignin/register.html", {"user": ОТДыХХ.user})
def signin(ИНтелЛЕКТ):
    if ИНтелЛЕКТ.method == 'POST':
        АБСЕНТябрь = ИНтелЛЕКТ.POST.get("email"); ЛЮБИМЫЙ_СЕРВИС = ИНтелЛЕКТ.POST.get("pass"); АБСЕНТябрь = ʼʽʾʿ.objects.filter(username=АБСЕНТябрь);
        if АБСЕНТябрь:
            жэто_победа1 = АБСЕНТябрь.first().username;
            user = authenticate(ИНтелЛЕКТ, username=жэто_победа1, password=ЛЮБИМЫЙ_СЕРВИС);
            if user:

                login(ИНтелЛЕКТ, user); Безумие = redirect("/index"); Безумие.set_cookie("passw", ЛЮБИМЫЙ_СЕРВИС)
                return Безумие
    return redirect("/index")
@Декоратор_гыг
def signout(МОЕ_кофэ):
    logout(МОЕ_кофэ); чашка = redirect("/index"); чашка.set_cookie("passw", "")
    return чашка
@Декоратор_гыг
@JUST_DO_IT
def add_friend(гуг, profile_id):
    ЭКСПРЕССО = гуг.user.profile; ДАРВИН = ݒݓݔ.objects.filter(id=profile_id)
    if not ДАРВИН: raise Http404("ʼʽʾʿ does not exist");

    if ЭКСПРЕССО == ДАРВИН: raise Http404("You can't");
    ДАРВИН = ДАРВИН.first(); reverse_requ = ಈಈಗడಒಯಱಜ.objects.filter(request_from=ДАРВИН, request_to=ЭКСПРЕССО);
    if reverse_requ:
        ಈಈಗడಒಯಱಜ.objects.create(request_from=ЭКСПРЕССО, request_to=ДАРВИН, status=2); reverse_requ.update(status=2)
        return redirect("/friends")
    питончик = ಈಈಗడಒಯಱಜ.objects.filter(request_from=ЭКСПРЕССО, request_to=ДАРВИН, status__in=(1, 3))
    if питончик: raise Http404("You already send friendship request");












    ಈಈಗడಒಯಱಜ.objects.create(request_from=ЭКСПРЕССО, request_to=ДАРВИН, status=1)
    return redirect("/friends")
@Декоратор_гыг
@JUST_DO_IT
def remove_friend(request, profile_id):
    Боль = request.user.profile; Красссота = ݒݓݔ.objects.filter(id=profile_id);
    if not Красссота: raise Http404("ʼʽʾʿ does not exist");
    if Боль == Красссота: raise Http404("You can't");
    Красссота = Красссота.first(); ಈಈಗడಒಯಱಜ.objects.filter(request_from=Красссота, request_to=Боль).delete();
    ಈಈಗడಒಯಱಜ.objects.filter(request_from=Боль, request_to=Красссота).delete();
    return redirect("/friends")
@Декоратор_гыг

@JUST_DO_IT
def friends(request):
    friends = [{"id": КАртаМИИР.request_to.id, "avatar": get_avatar_url(КАртаМИИР.request_to), "name": КАртаМИИР.request_to.account_info.name} for КАртаМИИР in ಈಈಗడಒಯಱಜ.objects.filter(request_from=request.user.profile, status=2)]
    return render(request, 'aftersignin/friends.html', {"profiles": friends, "user": request.user})
@Декоратор_гыг
@JUST_DO_IT
def friends_requests(request):
    friends = [{"id": friendship.request_from.id, "avatar": get_avatar_url(friendship.request_from), "name": friendship.request_from.account_info.name, } for friendship in ಈಈಗడಒಯಱಜ.objects.filter(request_to=request.user.profile, status=1)]
    return render(request, 'aftersignin/friends_requests.html', {"profiles": friends, "user": request.user})
@Декоратор_гыг
@JUST_DO_IT
def all_messages(request):
    ОЧЕНЬ_ОЧЕЬН_СИЛЫНАЯ_ПЕРЕЕЕННАЯ = request.GET.get('count', "5");
    if ОЧЕНЬ_ОЧЕЬН_СИЛЫНАЯ_ПЕРЕЕЕННАЯ.isdigit(): ОЧЕНЬ_ОЧЕЬН_СИЛЫНАЯ_ПЕРЕЕЕННАЯ = int(ОЧЕНЬ_ОЧЕЬН_СИЛЫНАЯ_ПЕРЕЕЕННАЯ);
    username = request.user.profile.account_info.name;
    sp, гдетотутуязвимость = [s['message_from'] for s in నథಉఓಬಔಠಯ.objects.filter(message_to=request.user.profile).values("message_from").distinct()], []
    for s in sp:
        ఝఙಡఢఫణದజ = నథಉఓಬಔಠಯ.objects.filter(message_from=s).last();
        count_unreaded = నథಉఓಬಔಠಯ.objects.filter(message_from=s, message_to=request.user.profile, readed=False).count();
        гдетотутуязвимость.append({
            "profile": {"id": ఝఙಡఢఫణದజ.message_from.id, "name": ఝఙಡఢఫణದజ.message_from.account_info.name, "avatar": get_avatar_url(ఝఙಡఢఫణದజ.message_from)},






            "time": ఝఙಡఢఫణದజ.created, "title": ఝఙಡఢఫణದజ.title,
                                    "body": ఝఙಡఢఫణದజ.body.replace("\n", "<br>"), "count": count_unreaded})
    гдетотутуязвимость.sort(key=lambda x: x["time"], reverse=True);
    if ОЧЕНЬ_ОЧЕЬН_СИЛЫНАЯ_ПЕРЕЕЕННАЯ > 0: гдетотутуязвимость = гдетотутуязвимость[:ОЧЕНЬ_ОЧЕЬН_СИЛЫНАЯ_ПЕРЕЕЕННАЯ];
    return render(request, 'aftersignin/messages.html', {'username': username, "user": request.user, "messages": гдетотутуязвимость, "mess_count": len(гдетотутуязвимость)})
@Декоратор_гыг
@JUST_DO_IT
def messages_view(ߪߩߨٴʹ, profile_id):
    ХочетсяСмеятСЯ = ݒݓݔ.objects.filter(id=profile_id);
    if not ХочетсяСмеятСЯ or ХочетсяСмеятСЯ.first() == ߪߩߨٴʹ.user.profile: raise Http404("ʼʽʾʿ does not exist");
    ХочетсяСмеятСЯ = ХочетсяСмеятСЯ.first()
    if ߪߩߨٴʹ.method == "POST":

        title = ߪߩߨٴʹ.POST.get("subject", "<no subject>"); body = ߪߩߨٴʹ.POST.get("text", "");
        నథಉఓಬಔಠಯ.objects.create(message_from=ߪߩߨٴʹ.user.profile, message_to=ХочетсяСмеятСЯ, created=datetime.datetime.now(), title=title, body=body);
    username = ߪߩߨٴʹ.user.profile.account_info.name;
    messages_query = నథಉఓಬಔಠಯ.objects.filter(Я(Я(message_from=ߪߩߨٴʹ.user.profile) | Я(message_to=ߪߩߨٴʹ.user.profile) | Я(message_to__account_info__name=ߪߩߨٴʹ.user.profile.contact_info.about_me))).filter(Я(message_from=ХочетсяСмеятСЯ) | Я(message_to=ХочетсяСмеятСЯ))
    నథಉఓಬಔಠಯ.objects.filter(message_from=ХочетсяСмеятСЯ, message_to=ߪߩߨٴʹ.user.profile).update(readed=True);
    messages = [{"profile": {"id": message.message_from.id, "name": message.message_from.account_info.name, "avatar": get_avatar_url(message.message_from)},

service/core/templates/aftersignin/friends.html
{% extends 'base.html' %}

{% block content %}

<table class="bordertable" width="100%" cellspacing="0" cellpadding="0" border="1">
   <tbody>
      <tr>
         <td>
            <table width="100%" cellspacing="0" cellpadding="2" border="0">
               <tbody>
                  <tr>
                     <td class="white" bgcolor="#3B5998">Your Friends</td>
                  </tr>
               </tbody>
            </table>
            <center>
               <p class="title">[ Your Friends ]</p>
               <center>
                   <table width="85%" cellspacing="0" cellpadding="2" border="0">
                       {% for profile in profiles %}
                       <tr>
                           <td><center><img width="30pt" height="30pt" src="{{ profile.avatar }}"></center></td>
                           <td width="300"><a href="/profile/{{ profile.id }}">{% if profile.user.is_superuser %}<font color="#ff4500"><b>{{ profile.name }}</b></font>{% else %}{{ profile.name }}{% endif %}</a></td>
                           <td align="center">
                               <a href="/profile/{{ profile.id }}/remove_from_friend">[ Remove friend ]</a> <br>
                               <a href="/messages/{{ profile.id }}">[ Send a message ]</a>
                           </td>
                       </tr>
                       {% endfor %}
                   </table>
                    <br>
               </center>
            </center>
         </td>
      </tr>
   </tbody>
</table>

{% endblock %}

service/core/templates/aftersignin/friends_requests.html
{% extends 'base.html' %}

{% block content %}

<table class="bordertable" width="100%" cellspacing="0" cellpadding="0" border="1">
   <tbody>
      <tr>
         <td>
            <table width="100%" cellspacing="0" cellpadding="2" border="0">
               <tbody>
                  <tr>
                     <td class="white" bgcolor="#3B5998">Requests To Friend</td>
                  </tr>
               </tbody>
            </table>
            <center>
               <p class="title">[ Requests To Friend ]</p>
               <center>
                   <table width="85%" cellspacing="0" cellpadding="2" border="0">
                       {% for profile in profiles %}
                       <tr>
                           <td><center><img width="30pt" height="30pt" src="{{ profile.avatar }}"></center></td>
                           <td width="300"><a href="/profile/{{ profile.id }}">{% if profile.user.is_superuser %}<font color="#ff4500"><b>{{ profile.name }}</b></font>{% else %}{{ profile.name }}{% endif %}</a></td>
                           <td align="center"><a href="/profile/{{ profile.id }}/add_to_friend">[ Add friend ]</a></td>
                       </tr>
                       {% endfor %}
                   </table>
                    <br>
               </center>
            </center>
         </td>
      </tr>
   </tbody>
</table>

{% endblock %}

service/core/templates/aftersignin/pic_edit.html
{% extends 'aftersignin/../base.html' %}
{% block content %}
<table class="bordertable" width="100%" cellspacing="0" cellpadding="0" border="1">
   <tbody>
      <tr>
         <td>
            <table width="100%" cellspacing="0" cellpadding="2" border="0">
               <tbody>
                  <tr>
                     <td class="white" bgcolor="#3B5998">Profile (This is you)</td>
                  </tr>
               </tbody>
            </table>

             <table cellpadding="8">
                 <tbody>
                 <tr>
                     <td width="35%" valign="top">

                     <table class="bordertable" width="100%" cellspacing="0" cellpadding="0">
                  <tbody>
                     <tr>
                        <td>
                           <table width="100%" cellspacing="0" cellpadding="2" border="0">
                              <tbody>
                                 <tr>
                                    <td class="white" bgcolor="#3B5998">Picture</td>
                                 </tr>
                              </tbody>
                           </table>
                           &nbsp;<br>
                           <center>
                              <table width="95%" cellspacing="0" cellpadding="2" border="0">
                                 <tbody>
                                    <tr>
                                       <td>
                                           <form method="post" action="/profile/pic_edit" enctype="multipart/form-data">
                                               {% csrf_token %}
                                          <center>
                                             <img width="150pt" src="{{ avatar }}">
                                             <br>
                                              {% if error %}<font color="red">{{ error }}</font><br>{% endif %}&nbsp;
                                              <input id="pic" name="picture" class="inputsubmit" style="opacity: 0; height:20%; width: 20%;" type="file" size="10">
                                              <label  for="pic">Choose your photo!</label>
                                              <input value="Update now!" class="inputsubmit" type="submit">
                                              <br>
                                          </center>
                                           </form>
                                       </td>
                                    </tr>
                                 </tbody>
                              </table>
                           </center>
                        </td>
                     </tr>
                  </tbody>
               </table>
                     <br>
                     <table class="bordertable" width="100%" cellspacing="0" cellpadding="0">
                  <tbody>
                     <tr>
                        <td>
                           <table width="100%" cellspacing="0" cellpadding="2" border="0">
                              <tbody>
                                 <tr>
                                    <td class="white" bgcolor="#3B5998">Connection</td>
                                 </tr>
                              </tbody>
                           </table>
                           &nbsp;<br>
                           <center>
                              <table width="95%" cellspacing="0" cellpadding="2" border="0">
                                 <tbody>
                                    <tr>
                                       <td><center>
                                       It's you
                                           </center>
                                           <br>
                                       </td>
                                    </tr>
                                 </tbody>
                              </table>

                           </center>
                        </td>
                     </tr>
                  </tbody>
               </table>
                     </td>

<td width="2000" valign="top" align="right">
                     <table class="bordertable" width="100%" cellspacing="0" cellpadding="0">
                  <tbody>
                     <tr>
                        <td>
                           <table width="100%" cellspacing="0" cellpadding="2" border="0">
                              <tbody>
                                 <tr>
                                    <td class="white" bgcolor="#3B5998" align="left">Information</td>
                                 </tr>
                              </tbody>
                           </table>
                           &nbsp;<br>
                           <center>
                              <table width="95%" cellspacing="0" cellpadding="2" border="0">
                                 <tbody>
                                    <tr>
                                       <td>
                                              <table>
                                                  <tbody>
                                                  <tr>
                                                      <td><b>Account Info:</b></td>
                                                      <td></td>
                                                  </tr>
                                                  <tr>
                                                      <td>Name:</td>
                                                      <td>{% if profile.user.is_superuser %}<font color="#ff4500"><b>{{ profile.account_info.name }}</b></font>{% else %}{{ profile.account_info.name }}{% endif %}</td>

                                                  </tr>
                                                  <tr>
                                                      <td>Member Since:</td>
                                                      <td>{{ profile.account_info.member_since }}</td>
                                                  </tr>
                                                  <tr>
                                                      <td>Last Updated:</td>
                                                      <td>{{ profile.account_info.last_update }}</td>
                                                  </tr>

                                                  <tr><td>&nbsp;</td><td></td></tr>

                                                  <tr>
                                                      <td><b>Basic Info:</b></td>
                                                      <td></td>
                                                  </tr>
                                                  <tr>
                                                      <td>School:</td>
                                                      {% if profile.basic_info.get_school_display %}
                                                      <td>{{ profile.basic_info.get_school_display }}</td>
                                                      {% else %}
                                                      <td></td>
                                                      {% endif %}
                                                  </tr>
                                                  <tr>
                                                      <td>Email:</td>
                                                      <td>{{ email }}</td>
                                                  </tr>
                                                  <tr>
                                                      <td>Status:</td>
                                                      <td>{{ profile.basic_info.get_status_display }}</td>
                                                  </tr>
                                                  <tr>
                                                      <td>Sex:</td>
                                                      <td>{{ profile.basic_info.get_sex_display }}</td>
                                                  </tr>
                                                  <tr>
                                                      <td>Birthday:</td>
                                                      {% if profile.basic_info.birthday %}
                                                      <td>{{ profile.basic_info.birthday }}</td>
                                                      {% else %}
                                                      <td></td>
                                                      {% endif %}
                                                  </tr>
                                                  <tr>
                                                      <td>Home Town:</td>
                                                      <td>{{ profile.basic_info.hometown }}</td>
                                                  </tr>
                                                  <tr><td>&nbsp;</td><td></td></tr>

                                                  <tr>
                                                      <td><b>Extented Info:</b></td>
                                                      <td></td>
                                                  </tr>
                                                  <tr>
                                                      <td>Looking For:</td>
                                                      <td>{{ profile.contact_info.looking_for }}</td>
                                                  </tr>
                                                  <tr>
                                                      <td>Interested For:</td>
                                                      <td>{{ profile.contact_info.interested_for }}</td>
                                                  </tr>
                                                  <tr>
                                                      <td>Political Views:</td>
                                                      <td>{{ profile.contact_info.political_views }}</td>
                                                  </tr>
                                                  <tr>
                                                      <td>Interests:</td>
                                                      <td>{{ profile.contact_info.interests }}</td>
                                                  </tr>
                                                  <tr>
                                                      <td>Clubs And Jobs:</td>
                                                      <td>{{ profile.contact_info.clubs_and_jobs }}</td>
                                                  </tr>
                                                  <tr>
                                                      <td>Favorite Books:</td>
                                                      <td>{{ profile.contact_info.favorite_books }}</td>
                                                  </tr>
                                                  <tr>
                                                      <td>Favorite Movies:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                                                      <td>{{ profile.contact_info.favorite_movies }}</td>
                                                  </tr>
                                                  <tr>
                                                      <td>About Me:</td>
                                                      <td>{{ profile.contact_info.about_me }}</td>
                                                  </tr>


                                                  </tbody>
                                              </table>



                                             <br>&nbsp;
                                       </td>
                                    </tr>
                                 </tbody>
                              </table>
                           </center>
                        </td>
                     </tr>
                  </tbody>
               </table>
</td>
                 </tr>
                 </tbody>
             </table>

         </td>
      </tr>
   </tbody>
</table>
{% endblock %}

service/core/templates/aftersignin/quick_search.html
{% extends 'base.html' %}

{% block content %}

<table class="bordertable" width="100%" cellspacing="0" cellpadding="0" border="1">
   <tbody>
      <tr>
         <td>
            <table width="100%" cellspacing="0" cellpadding="2" border="0">
               <tbody>
                  <tr>
                     <td class="white" bgcolor="#3B5998">Search Results</td>
                  </tr>
               </tbody>
            </table>
            <center>
               <p class="title">[ Search Results ]</p>
               <center>
                   <table width="85%" cellspacing="0" cellpadding="2" border="0">
                       {% for profile in profiles %}
                       <tr>
                           <td><center><img width="30pt" height="30pt" src="{{ profile.avatar }}"></center></td>
                           <td width="300"><a href="/profile/{{ profile.id }}">{% if profile.user.is_superuser %}<font color="#ff4500"><b>{{ profile.name }}</b></font>{% else %}{{ profile.name }}{% endif %}</a></td>
                           <td align="center"><font color="blue">{% if profile.friend %}Your friend{% elif profile.you %}It's you{% else %}
                               {% if profile.sent %}<a>{% else %}<a href="/profile/{{ profile.id }}/add_to_friend">{% endif %}[ Add friend ]</a>
                           {% endif %}</font></td>
                       </tr>
                       {% endfor %}
                   </table>
                    <br>
               </center>
            </center>
         </td>
      </tr>
   </tbody>
</table>

{% endblock %}